//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Governament_SC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Entry_No { get; set; }
        public string Type { get; set; }
        public Nullable<int> E_id { get; set; }
        public Nullable<int> Sell_ID { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public Nullable<int> Credit { get; set; }
        public Nullable<int> Debit { get; set; }
    
        public virtual Expense Expense { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
