//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Governament_SC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expense()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int E_ID { get; set; }
        public Nullable<int> Incentives_ID { get; set; }
        public Nullable<int> Stock_ID { get; set; }
        public Nullable<int> Bill_ID { get; set; }
        public Nullable<int> I_ID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public Nullable<int> Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Bill Bill { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual Incentive Incentive { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
